import type { Langue } from '@/lib/config/maquette'

export type DomaineId = 'vtc' | 'sante' | 'restaurant' | 'architecte' | 'etudes' | 'formation' | 'autre'

export type Editorial = {
  enseigne: string
  /** Surtitre du héros : le secteur, pas le slogan. Une ligne, jamais deux. */
  surtitre: string
  /** Trois pages du socle puis les douze des tranches : sert aussi à nommer les pages rédigées. */
  pages: string[]
  titre: string
  corps: string
  services: { nom: string; texte: string }[]
  blocsRepris: string[]
  articles: { titre: string; requete: string }[]
  recherche: { titre: string; description: string }
}

export const DOMAINES = [
  { id: 'vtc', libelle: 'VTC et transport de personnes' },
  { id: 'sante', libelle: 'Praticien de santé' },
  { id: 'restaurant', libelle: 'Restaurant ou commerce' },
  { id: 'architecte', libelle: 'Cabinet d’architectes' },
  { id: 'etudes', libelle: 'Bureau d’études' },
  { id: 'formation', libelle: 'Coach ou formateur' },
  { id: 'autre', libelle: 'Autre activité' },
] as const satisfies readonly { id: DomaineId; libelle: string }[]

export const DOMAINE_DEFAUT: DomaineId = 'autre'

/** Entreprises fictives, aucune référence ni avis réels. Aucun chiffre présenté comme une
 *  mesure de NMW Studios : les délais cités appartiennent à l’entreprise inventée. */
export const EDITORIAL: Record<DomaineId, Record<Langue, Editorial>> = {
  vtc: {
    fr: {
      enseigne: 'Trajets Garonne',
      surtitre: 'Bordeaux et Gironde',
      pages: ['Accueil', 'Prestations', 'Réserver', 'Tarifs', 'Aéroport', 'Gare Saint-Jean', 'Longue distance', 'Mise à disposition', 'Zones desservies', 'Le véhicule', 'Entreprises', 'Événements', 'À propos', 'Contact', 'Mentions légales'],
      titre: 'Votre chauffeur à Bordeaux, réservé la veille',
      corps: 'Aéroport, gare, longue distance et mise à disposition. Berline, tarif connu avant le départ.',
      services: [
        { nom: 'Aéroport et gare', texte: 'Suivi du vol, attente comprise, prise en charge en salle d’arrivée.' },
        { nom: 'Longue distance', texte: 'Bordeaux vers Arcachon, Toulouse ou Paris, au forfait annoncé.' },
        { nom: 'Mise à disposition', texte: 'Un chauffeur à l’heure ou à la journée pour vos déplacements.' },
      ],
      blocsRepris: ['Nos prestations', 'Le véhicule', 'Nous joindre'],
      articles: [
        { titre: 'Combien coûte un VTC pour l’aéroport', requete: 'prix vtc aéroport bordeaux' },
        { titre: 'VTC ou taxi, lequel choisir', requete: 'vtc ou taxi bordeaux' },
        { titre: 'Réserver un chauffeur pour un mariage', requete: 'chauffeur mariage gironde' },
        { titre: 'Bordeaux vers Arcachon avec chauffeur', requete: 'vtc bordeaux arcachon' },
        { titre: 'Rejoindre la gare sans stress', requete: 'vtc gare saint-jean' },
        { titre: 'Ce que couvre une mise à disposition', requete: 'mise à disposition chauffeur' },
        { titre: 'Voyager avec un siège enfant', requete: 'vtc siège enfant bordeaux' },
        { titre: 'Déplacements professionnels et notes de frais', requete: 'vtc entreprise bordeaux' },
        { titre: 'Annuler une réservation', requete: 'annulation vtc conditions' },
        { titre: 'Rouler la nuit en Gironde', requete: 'vtc nuit bordeaux' },
      ],
      recherche: { titre: 'Trajets Garonne · VTC à Bordeaux et en Gironde', description: 'Chauffeur privé pour l’aéroport, la gare et la longue distance. Tarif annoncé avant le départ.' },
    },
    en: {
      enseigne: 'Trajets Garonne',
      surtitre: 'Bordeaux and Gironde',
      pages: ['Home', 'Services', 'Book', 'Rates', 'Airport', 'Train station', 'Long distance', 'Hourly hire', 'Areas covered', 'The car', 'Business', 'Events', 'About', 'Contact', 'Legal'],
      titre: 'Your driver in Bordeaux, booked the day before',
      corps: 'Airport, station, long distance and hourly hire. Saloon car, fare known before you leave.',
      services: [
        { nom: 'Airport and station', texte: 'Flight tracking, waiting time included, met in the arrivals hall.' },
        { nom: 'Long distance', texte: 'Bordeaux to Arcachon, Toulouse or Paris at an agreed flat rate.' },
        { nom: 'Hourly hire', texte: 'A driver by the hour or by the day for your business travel.' },
      ],
      blocsRepris: ['Our services', 'The car', 'Get in touch'],
      articles: [
        { titre: 'What a ride to the airport costs', requete: 'vtc price bordeaux airport' },
        { titre: 'Private hire or taxi, which to pick', requete: 'vtc or taxi bordeaux' },
        { titre: 'Booking a driver for a wedding', requete: 'wedding driver gironde' },
        { titre: 'Bordeaux to Arcachon with a driver', requete: 'private driver bordeaux arcachon' },
        { titre: 'Reaching the station without stress', requete: 'private hire saint-jean station' },
        { titre: 'What hourly hire covers', requete: 'hourly driver hire bordeaux' },
        { titre: 'Travelling with a child seat', requete: 'child seat private hire bordeaux' },
        { titre: 'Business travel and expense claims', requete: 'corporate driver bordeaux' },
        { titre: 'Cancelling a booking', requete: 'private hire cancellation terms' },
        { titre: 'Driving at night in Gironde', requete: 'night driver bordeaux' },
      ],
      recherche: { titre: 'Trajets Garonne · Private driver in Bordeaux', description: 'Private hire for the airport, the station and long distance. Fare agreed before departure.' },
    },
    es: {
      enseigne: 'Trajets Garonne',
      surtitre: 'Burdeos y Gironda',
      pages: ['Inicio', 'Servicios', 'Reservar', 'Tarifas', 'Aeropuerto', 'Estación', 'Larga distancia', 'Por horas', 'Zonas cubiertas', 'El vehículo', 'Empresas', 'Eventos', 'Quiénes somos', 'Contacto', 'Aviso legal'],
      titre: 'Su chófer en Burdeos, reservado el día antes',
      corps: 'Aeropuerto, estación, larga distancia y servicio por horas. Berlina, tarifa conocida antes de salir.',
      services: [
        { nom: 'Aeropuerto y estación', texte: 'Seguimiento del vuelo, espera incluida, recogida en la sala de llegadas.' },
        { nom: 'Larga distancia', texte: 'Burdeos hacia Arcachon, Toulouse o París, con tarifa acordada.' },
        { nom: 'Servicio por horas', texte: 'Un chófer por horas o por día para sus desplazamientos.' },
      ],
      blocsRepris: ['Nuestros servicios', 'El vehículo', 'Contactar'],
      articles: [
        { titre: 'Cuánto cuesta un traslado al aeropuerto', requete: 'precio vtc aeropuerto burdeos' },
        { titre: 'VTC o taxi, cuál elegir', requete: 'vtc o taxi burdeos' },
        { titre: 'Reservar chófer para una boda', requete: 'chófer boda gironda' },
        { titre: 'Burdeos a Arcachon con chófer', requete: 'vtc burdeos arcachon' },
        { titre: 'Llegar a la estación sin prisas', requete: 'vtc estación saint-jean' },
        { titre: 'Qué incluye el servicio por horas', requete: 'chófer por horas burdeos' },
        { titre: 'Viajar con silla infantil', requete: 'vtc silla infantil burdeos' },
        { titre: 'Viajes de empresa y gastos', requete: 'vtc empresa burdeos' },
        { titre: 'Cancelar una reserva', requete: 'cancelación vtc condiciones' },
        { titre: 'Conducir de noche en Gironda', requete: 'vtc noche burdeos' },
      ],
      recherche: { titre: 'Trajets Garonne · VTC en Burdeos y Gironda', description: 'Chófer privado para el aeropuerto, la estación y la larga distancia. Tarifa acordada antes de salir.' },
    },
    de: {
      enseigne: 'Trajets Garonne',
      surtitre: 'Bordeaux und Gironde',
      pages: ['Startseite', 'Leistungen', 'Buchen', 'Preise', 'Flughafen', 'Bahnhof', 'Fernstrecken', 'Stundenweise', 'Einsatzgebiet', 'Das Fahrzeug', 'Firmen', 'Veranstaltungen', 'Über uns', 'Kontakt', 'Impressum'],
      titre: 'Ihr Fahrer in Bordeaux, am Vortag gebucht',
      corps: 'Flughafen, Bahnhof, Fernstrecken und stundenweise Fahrten. Limousine, Preis vor der Abfahrt bekannt.',
      services: [
        { nom: 'Flughafen und Bahnhof', texte: 'Flugverfolgung, Wartezeit inbegriffen, Empfang in der Ankunftshalle.' },
        { nom: 'Fernstrecken', texte: 'Bordeaux nach Arcachon, Toulouse oder Paris zum vereinbarten Festpreis.' },
        { nom: 'Stundenweise', texte: 'Ein Fahrer pro Stunde oder pro Tag für Ihre Geschäftsreisen.' },
      ],
      blocsRepris: ['Unsere Leistungen', 'Das Fahrzeug', 'Kontakt aufnehmen'],
      articles: [
        { titre: 'Was eine Fahrt zum Flughafen kostet', requete: 'preis fahrdienst flughafen bordeaux' },
        { titre: 'Fahrdienst oder Taxi, was passt', requete: 'fahrdienst oder taxi bordeaux' },
        { titre: 'Fahrer für eine Hochzeit buchen', requete: 'hochzeitsfahrer gironde' },
        { titre: 'Bordeaux nach Arcachon mit Fahrer', requete: 'fahrdienst bordeaux arcachon' },
        { titre: 'Ohne Stress zum Bahnhof', requete: 'fahrdienst bahnhof saint-jean' },
        { titre: 'Was stundenweise Fahrten umfassen', requete: 'fahrer stundenweise bordeaux' },
        { titre: 'Reisen mit Kindersitz', requete: 'kindersitz fahrdienst bordeaux' },
        { titre: 'Geschäftsreisen und Spesen', requete: 'firmenfahrdienst bordeaux' },
        { titre: 'Eine Buchung stornieren', requete: 'fahrdienst stornobedingungen' },
        { titre: 'Nachts in der Gironde fahren', requete: 'nachtfahrdienst bordeaux' },
      ],
      recherche: { titre: 'Trajets Garonne · Fahrdienst in Bordeaux', description: 'Privatfahrer für Flughafen, Bahnhof und Fernstrecken. Preis vor der Abfahrt vereinbart.' },
    },
  },
  sante: {
    fr: {
      enseigne: 'Cabinet Belvédère',
      surtitre: 'Cabinet de kinésithérapie',
      pages: ['Accueil', 'Le cabinet', 'Rendez-vous', 'Kinésithérapie du sport', 'Rééducation du dos', 'Suites opératoires', 'Première séance', 'Tarifs et remboursement', 'Accès et horaires', 'L’équipe', 'Questions fréquentes', 'Conseils', 'Contact', 'Mentions légales', 'Plan du site'],
      titre: 'Kinésithérapie du sport et du dos, à Bordeaux',
      corps: 'Bilan, rééducation et prévention. Rendez-vous en ligne, cabinet accessible de plain-pied.',
      services: [
        { nom: 'Bilan et diagnostic', texte: 'Une première séance longue, pour comprendre la douleur avant de la traiter.' },
        { nom: 'Rééducation', texte: 'Un protocole revu à chaque séance, avec des exercices à faire chez vous.' },
        { nom: 'Prévention', texte: 'Reprendre le sport ou le travail sans rejouer la même blessure.' },
      ],
      blocsRepris: ['Le cabinet', 'Nos soins', 'Prendre rendez-vous'],
      articles: [
        { titre: 'Combien de séances pour un lumbago', requete: 'séances kiné lumbago' },
        { titre: 'Kiné du sport, quand consulter', requete: 'kiné du sport bordeaux' },
        { titre: 'Ce qu’il faut apporter à la première séance', requete: 'première séance kiné' },
        { titre: 'Tendinite d’épaule, que faire', requete: 'tendinite épaule kiné' },
        { titre: 'Reprendre la course après une entorse', requete: 'reprise course entorse cheville' },
        { titre: 'Remboursement des séances', requete: 'remboursement kiné mutuelle' },
        { titre: 'Mal de dos au bureau', requete: 'mal de dos bureau exercices' },
        { titre: 'Rééducation après une opération du genou', requete: 'rééducation genou opération' },
        { titre: 'Faut-il une ordonnance', requete: 'kiné sans ordonnance' },
        { titre: 'Trois étirements pour le soir', requete: 'étirements dos le soir' },
      ],
      recherche: { titre: 'Cabinet Belvédère · Kinésithérapie à Bordeaux', description: 'Bilan, rééducation et prévention. Rendez-vous en ligne, cabinet accessible de plain-pied.' },
    },
    en: {
      enseigne: 'Cabinet Belvédère',
      surtitre: 'Physiotherapy practice',
      pages: ['Home', 'The practice', 'Appointments', 'Sports physiotherapy', 'Back rehabilitation', 'After surgery', 'First session', 'Fees and cover', 'Getting here', 'The team', 'FAQ', 'Advice', 'Contact', 'Legal', 'Sitemap'],
      titre: 'Sports and back physiotherapy in Bordeaux',
      corps: 'Assessment, rehabilitation and prevention. Book online, step-free practice.',
      services: [
        { nom: 'Assessment', texte: 'A long first session, to understand the pain before treating it.' },
        { nom: 'Rehabilitation', texte: 'A plan reviewed every session, with exercises to do at home.' },
        { nom: 'Prevention', texte: 'Back to sport or to work without repeating the same injury.' },
      ],
      blocsRepris: ['The practice', 'Our care', 'Book an appointment'],
      articles: [
        { titre: 'How many sessions for lower back pain', requete: 'physio sessions lower back pain' },
        { titre: 'Sports physio, when to come in', requete: 'sports physio bordeaux' },
        { titre: 'What to bring to the first session', requete: 'first physio session' },
        { titre: 'Shoulder tendinitis, what to do', requete: 'shoulder tendinitis physio' },
        { titre: 'Running again after a sprain', requete: 'running after ankle sprain' },
        { titre: 'Getting sessions reimbursed', requete: 'physio reimbursement cover' },
        { titre: 'Back pain at a desk', requete: 'desk back pain exercises' },
        { titre: 'Rehabilitation after knee surgery', requete: 'knee surgery rehabilitation' },
        { titre: 'Do you need a referral', requete: 'physio without referral' },
        { titre: 'Three evening stretches', requete: 'evening back stretches' },
      ],
      recherche: { titre: 'Cabinet Belvédère · Physiotherapy in Bordeaux', description: 'Assessment, rehabilitation and prevention. Book online, step-free practice.' },
    },
    es: {
      enseigne: 'Cabinet Belvédère',
      surtitre: 'Consulta de fisioterapia',
      pages: ['Inicio', 'La consulta', 'Citas', 'Fisioterapia deportiva', 'Rehabilitación de espalda', 'Postoperatorio', 'Primera sesión', 'Tarifas y reembolso', 'Cómo llegar', 'El equipo', 'Preguntas', 'Consejos', 'Contacto', 'Aviso legal', 'Mapa del sitio'],
      titre: 'Fisioterapia deportiva y de espalda en Burdeos',
      corps: 'Valoración, rehabilitación y prevención. Cita en línea, consulta sin escalones.',
      services: [
        { nom: 'Valoración', texte: 'Una primera sesión larga, para entender el dolor antes de tratarlo.' },
        { nom: 'Rehabilitación', texte: 'Un plan revisado en cada sesión, con ejercicios para casa.' },
        { nom: 'Prevención', texte: 'Volver al deporte o al trabajo sin repetir la misma lesión.' },
      ],
      blocsRepris: ['La consulta', 'Nuestros cuidados', 'Pedir cita'],
      articles: [
        { titre: 'Cuántas sesiones para una lumbalgia', requete: 'sesiones fisio lumbalgia' },
        { titre: 'Fisioterapia deportiva, cuándo acudir', requete: 'fisioterapia deportiva burdeos' },
        { titre: 'Qué llevar a la primera sesión', requete: 'primera sesión fisioterapia' },
        { titre: 'Tendinitis de hombro, qué hacer', requete: 'tendinitis hombro fisioterapia' },
        { titre: 'Volver a correr tras un esguince', requete: 'correr después esguince tobillo' },
        { titre: 'Reembolso de las sesiones', requete: 'reembolso fisioterapia mutua' },
        { titre: 'Dolor de espalda en la oficina', requete: 'dolor espalda oficina ejercicios' },
        { titre: 'Rehabilitación tras operación de rodilla', requete: 'rehabilitación rodilla operación' },
        { titre: 'Hace falta receta médica', requete: 'fisioterapia sin receta' },
        { titre: 'Tres estiramientos para la noche', requete: 'estiramientos espalda noche' },
      ],
      recherche: { titre: 'Cabinet Belvédère · Fisioterapia en Burdeos', description: 'Valoración, rehabilitación y prevención. Cita en línea, consulta sin escalones.' },
    },
    de: {
      enseigne: 'Cabinet Belvédère',
      surtitre: 'Physiotherapiepraxis',
      pages: ['Startseite', 'Die Praxis', 'Termine', 'Sportphysiotherapie', 'Rückentherapie', 'Nach der Operation', 'Erste Sitzung', 'Preise und Erstattung', 'Anfahrt', 'Das Team', 'Fragen', 'Tipps', 'Kontakt', 'Impressum', 'Sitemap'],
      titre: 'Sport- und Rückenphysiotherapie in Bordeaux',
      corps: 'Befund, Rehabilitation und Vorbeugung. Termin online, Praxis ebenerdig zugänglich.',
      services: [
        { nom: 'Befund', texte: 'Eine lange erste Sitzung, um den Schmerz zu verstehen, bevor er behandelt wird.' },
        { nom: 'Rehabilitation', texte: 'Ein Plan, der jede Sitzung überprüft wird, mit Übungen für daheim.' },
        { nom: 'Vorbeugung', texte: 'Zurück zum Sport oder zur Arbeit, ohne dieselbe Verletzung zu wiederholen.' },
      ],
      blocsRepris: ['Die Praxis', 'Unsere Behandlungen', 'Termin vereinbaren'],
      articles: [
        { titre: 'Wie viele Sitzungen bei Hexenschuss', requete: 'sitzungen physiotherapie hexenschuss' },
        { titre: 'Sportphysiotherapie, wann kommen', requete: 'sportphysiotherapie bordeaux' },
        { titre: 'Was zur ersten Sitzung mitbringen', requete: 'erste sitzung physiotherapie' },
        { titre: 'Schultersehnenentzündung, was tun', requete: 'schulter sehnenentzündung physiotherapie' },
        { titre: 'Nach einer Bänderzerrung wieder laufen', requete: 'laufen nach bänderzerrung' },
        { titre: 'Erstattung der Sitzungen', requete: 'erstattung physiotherapie kasse' },
        { titre: 'Rückenschmerzen im Büro', requete: 'rückenschmerzen büro übungen' },
        { titre: 'Rehabilitation nach Knieoperation', requete: 'rehabilitation knie operation' },
        { titre: 'Braucht man eine Verordnung', requete: 'physiotherapie ohne verordnung' },
        { titre: 'Drei Dehnübungen für den Abend', requete: 'dehnübungen rücken abend' },
      ],
      recherche: { titre: 'Cabinet Belvédère · Physiotherapie in Bordeaux', description: 'Befund, Rehabilitation und Vorbeugung. Termin online, Praxis ebenerdig zugänglich.' },
    },
  },
  restaurant: {
    fr: {
      enseigne: 'Table Belloc',
      surtitre: 'Bistrot de quartier',
      pages: ['Accueil', 'La carte', 'Réserver', 'Menu du midi', 'Le soir', 'Les vins', 'La maison', 'Le marché', 'Groupes', 'À emporter', 'Horaires et accès', 'Actualités', 'Contact', 'Mentions légales', 'Plan du site'],
      titre: 'Cuisine du marché, deux services par jour',
      corps: 'Une carte courte, réécrite chaque semaine selon ce que le marché donne le matin.',
      services: [
        { nom: 'Le midi', texte: 'Entrée, plat, dessert, décidés le matin selon les paniers reçus.' },
        { nom: 'Le soir, à la carte', texte: 'Six plats, deux desserts, et des vins de vignerons du coin.' },
        { nom: 'Groupes', texte: 'La salle du fond, jusqu’à douze personnes, sur réservation.' },
      ],
      blocsRepris: ['La maison', 'La carte', 'Réserver une table'],
      articles: [
        { titre: 'Où déjeuner près des Capucins', requete: 'déjeuner capucins bordeaux' },
        { titre: 'Pourquoi la carte change chaque semaine', requete: 'restaurant carte du marché bordeaux' },
        { titre: 'Réserver pour un groupe', requete: 'restaurant groupe bordeaux' },
        { titre: 'Ce que veut dire cuisine du marché', requete: 'cuisine du marché définition' },
        { titre: 'Nos vins de vignerons girondins', requete: 'vin de vigneron bordeaux restaurant' },
        { titre: 'Manger sans gluten chez nous', requete: 'restaurant sans gluten bordeaux' },
        { titre: 'Le menu du midi en semaine', requete: 'menu midi semaine bordeaux' },
        { titre: 'Venir avec des enfants', requete: 'restaurant avec enfants bordeaux' },
        { titre: 'Emporter un plat le dimanche', requete: 'plat à emporter dimanche bordeaux' },
        { titre: 'Nos horaires pendant les vacances', requete: 'restaurant horaires vacances bordeaux' },
      ],
      recherche: { titre: 'Table Belloc · Cuisine du marché à Bordeaux', description: 'Carte courte réécrite chaque semaine, deux services par jour. Réservation en ligne.' },
    },
    en: {
      enseigne: 'Table Belloc',
      surtitre: 'Neighbourhood bistro',
      pages: ['Home', 'Menu', 'Book', 'Lunch menu', 'Dinner', 'Wines', 'The house', 'The market', 'Groups', 'Takeaway', 'Hours and access', 'News', 'Contact', 'Legal', 'Sitemap'],
      titre: 'Market cooking, two services a day',
      corps: 'A short menu, rewritten every week from whatever the market gives us that morning.',
      services: [
        { nom: 'Lunch', texte: 'Starter, main, dessert, decided in the morning from the crates we get.' },
        { nom: 'Dinner, à la carte', texte: 'Six dishes, two desserts, and wines from growers nearby.' },
        { nom: 'Groups', texte: 'The back room, up to twelve people, by reservation.' },
      ],
      blocsRepris: ['The house', 'The menu', 'Book a table'],
      articles: [
        { titre: 'Where to have lunch near Les Capucins', requete: 'lunch capucins bordeaux' },
        { titre: 'Why the menu changes every week', requete: 'market menu restaurant bordeaux' },
        { titre: 'Booking for a group', requete: 'group restaurant bordeaux' },
        { titre: 'What market cooking means', requete: 'market cooking meaning' },
        { titre: 'Our wines from Gironde growers', requete: 'grower wine bordeaux restaurant' },
        { titre: 'Eating gluten free here', requete: 'gluten free restaurant bordeaux' },
        { titre: 'The weekday lunch menu', requete: 'weekday lunch menu bordeaux' },
        { titre: 'Coming with children', requete: 'restaurant with children bordeaux' },
        { titre: 'Takeaway on a Sunday', requete: 'sunday takeaway bordeaux' },
        { titre: 'Our holiday opening hours', requete: 'restaurant holiday hours bordeaux' },
      ],
      recherche: { titre: 'Table Belloc · Market cooking in Bordeaux', description: 'A short menu rewritten every week, two services a day. Book online.' },
    },
    es: {
      enseigne: 'Table Belloc',
      surtitre: 'Bistró de barrio',
      pages: ['Inicio', 'La carta', 'Reservar', 'Menú del mediodía', 'Por la noche', 'Los vinos', 'La casa', 'El mercado', 'Grupos', 'Para llevar', 'Horarios y acceso', 'Novedades', 'Contacto', 'Aviso legal', 'Mapa del sitio'],
      titre: 'Cocina de mercado, dos servicios al día',
      corps: 'Una carta corta, reescrita cada semana con lo que el mercado da por la mañana.',
      services: [
        { nom: 'Al mediodía', texte: 'Entrante, plato y postre, decididos por la mañana según las cajas recibidas.' },
        { nom: 'De noche, a la carta', texte: 'Seis platos, dos postres y vinos de viticultores de la zona.' },
        { nom: 'Grupos', texte: 'La sala del fondo, hasta doce personas, con reserva.' },
      ],
      blocsRepris: ['La casa', 'La carta', 'Reservar mesa'],
      articles: [
        { titre: 'Dónde comer cerca de Les Capucins', requete: 'comer capucins burdeos' },
        { titre: 'Por qué la carta cambia cada semana', requete: 'restaurante carta de mercado burdeos' },
        { titre: 'Reservar para un grupo', requete: 'restaurante grupo burdeos' },
        { titre: 'Qué significa cocina de mercado', requete: 'cocina de mercado significado' },
        { titre: 'Nuestros vinos de viticultores', requete: 'vino de viticultor burdeos restaurante' },
        { titre: 'Comer sin gluten aquí', requete: 'restaurante sin gluten burdeos' },
        { titre: 'El menú del mediodía entre semana', requete: 'menú mediodía semana burdeos' },
        { titre: 'Venir con niños', requete: 'restaurante con niños burdeos' },
        { titre: 'Comida para llevar el domingo', requete: 'comida para llevar domingo burdeos' },
        { titre: 'Nuestros horarios en vacaciones', requete: 'restaurante horarios vacaciones burdeos' },
      ],
      recherche: { titre: 'Table Belloc · Cocina de mercado en Burdeos', description: 'Carta corta reescrita cada semana, dos servicios al día. Reserva en línea.' },
    },
    de: {
      enseigne: 'Table Belloc',
      surtitre: 'Bistro im Viertel',
      pages: ['Startseite', 'Die Karte', 'Reservieren', 'Mittagsmenü', 'Abends', 'Die Weine', 'Das Haus', 'Der Markt', 'Gruppen', 'Zum Mitnehmen', 'Öffnungszeiten', 'Aktuelles', 'Kontakt', 'Impressum', 'Sitemap'],
      titre: 'Marktküche, zwei Servicezeiten am Tag',
      corps: 'Eine kurze Karte, jede Woche neu geschrieben, nach dem, was der Markt morgens hergibt.',
      services: [
        { nom: 'Mittags', texte: 'Vorspeise, Hauptgang, Nachtisch, morgens nach den gelieferten Kisten entschieden.' },
        { nom: 'Abends à la carte', texte: 'Sechs Gerichte, zwei Nachtische und Weine von Winzern aus der Nähe.' },
        { nom: 'Gruppen', texte: 'Der hintere Saal, bis zu zwölf Personen, nach Reservierung.' },
      ],
      blocsRepris: ['Das Haus', 'Die Karte', 'Tisch reservieren'],
      articles: [
        { titre: 'Wo man nahe Les Capucins isst', requete: 'mittagessen capucins bordeaux' },
        { titre: 'Warum die Karte jede Woche wechselt', requete: 'restaurant marktkarte bordeaux' },
        { titre: 'Für eine Gruppe reservieren', requete: 'gruppenrestaurant bordeaux' },
        { titre: 'Was Marktküche bedeutet', requete: 'marktküche bedeutung' },
        { titre: 'Unsere Weine von Winzern der Gironde', requete: 'winzerwein bordeaux restaurant' },
        { titre: 'Glutenfrei bei uns essen', requete: 'glutenfrei restaurant bordeaux' },
        { titre: 'Das Mittagsmenü unter der Woche', requete: 'mittagsmenü woche bordeaux' },
        { titre: 'Mit Kindern kommen', requete: 'restaurant mit kindern bordeaux' },
        { titre: 'Sonntags zum Mitnehmen', requete: 'sonntag zum mitnehmen bordeaux' },
        { titre: 'Unsere Ferienöffnungszeiten', requete: 'restaurant ferienzeiten bordeaux' },
      ],
      recherche: { titre: 'Table Belloc · Marktküche in Bordeaux', description: 'Kurze Karte, jede Woche neu, zwei Servicezeiten am Tag. Online reservieren.' },
    },
  },
  architecte: {
    fr: {
      enseigne: 'Atelier Bastide',
      surtitre: 'Agence d’architecture',
      pages: ['Accueil', 'L’agence', 'Contact', 'Réalisations', 'Réhabilitation', 'Extension', 'Local professionnel', 'Faisabilité', 'Méthode', 'Honoraires', 'L’équipe', 'Chantiers en cours', 'Presse', 'Mentions légales', 'Plan du site'],
      titre: 'Réhabiliter sans effacer',
      corps: 'Logement, échoppe et local professionnel. Étude de faisabilité avant tout engagement de travaux.',
      services: [
        { nom: 'Faisabilité', texte: 'Ce que le bâti et le règlement autorisent, avant d’engager des travaux.' },
        { nom: 'Réhabilitation', texte: 'Échoppe, immeuble ancien, grange : garder ce qui tient, refaire le reste.' },
        { nom: 'Suivi de chantier', texte: 'Consultation des entreprises, visites hebdomadaires, réception des travaux.' },
      ],
      blocsRepris: ['L’agence', 'Nos réalisations', 'Nous écrire'],
      articles: [
        { titre: 'Faut-il un architecte pour une extension', requete: 'architecte obligatoire extension' },
        { titre: 'Réhabiliter une échoppe bordelaise', requete: 'réhabilitation échoppe bordeaux' },
        { titre: 'Combien coûte une étude de faisabilité', requete: 'prix étude faisabilité architecte' },
        { titre: 'Permis de construire ou déclaration préalable', requete: 'permis ou déclaration préalable' },
        { titre: 'Isoler un mur en pierre sans le condamner', requete: 'isolation mur pierre ancien' },
        { titre: 'Surélever une maison en ville', requete: 'surélévation maison bordeaux' },
        { titre: 'Ce que contiennent nos honoraires', requete: 'honoraires architecte pourcentage' },
        { titre: 'Travailler avec les entreprises locales', requete: 'architecte consultation entreprises' },
        { titre: 'Transformer un local commercial en logement', requete: 'changement de destination local' },
        { titre: 'Un chantier en site occupé', requete: 'travaux en site occupé' },
      ],
      recherche: { titre: 'Atelier Bastide · Architectes à Bordeaux', description: 'Réhabilitation, extension et local professionnel. Étude de faisabilité avant travaux.' },
    },
    en: {
      enseigne: 'Atelier Bastide',
      surtitre: 'Architecture practice',
      pages: ['Home', 'The practice', 'Contact', 'Projects', 'Renovation', 'Extension', 'Commercial space', 'Feasibility', 'Method', 'Fees', 'The team', 'Current sites', 'Press', 'Legal', 'Sitemap'],
      titre: 'Renovating without erasing',
      corps: 'Homes, townhouses and commercial spaces. A feasibility study before any work is committed.',
      services: [
        { nom: 'Feasibility', texte: 'What the building and the planning rules allow, before committing to work.' },
        { nom: 'Renovation', texte: 'Townhouse, old block, barn: keep what holds, rebuild the rest.' },
        { nom: 'Site supervision', texte: 'Tendering, weekly visits, handover of the finished work.' },
      ],
      blocsRepris: ['The practice', 'Our projects', 'Write to us'],
      articles: [
        { titre: 'Do you need an architect for an extension', requete: 'architect required extension' },
        { titre: 'Renovating a Bordeaux townhouse', requete: 'townhouse renovation bordeaux' },
        { titre: 'What a feasibility study costs', requete: 'feasibility study architect price' },
        { titre: 'Full permit or prior notice', requete: 'planning permit or prior notice' },
        { titre: 'Insulating a stone wall without sealing it', requete: 'stone wall insulation old building' },
        { titre: 'Adding a storey in town', requete: 'adding a storey bordeaux' },
        { titre: 'What our fees cover', requete: 'architect fees percentage' },
        { titre: 'Working with local trades', requete: 'architect tendering trades' },
        { titre: 'Turning a shop into a home', requete: 'change of use shop to home' },
        { titre: 'Building while the place stays occupied', requete: 'works in occupied building' },
      ],
      recherche: { titre: 'Atelier Bastide · Architects in Bordeaux', description: 'Renovation, extension and commercial space. A feasibility study before any work.' },
    },
    es: {
      enseigne: 'Atelier Bastide',
      surtitre: 'Estudio de arquitectura',
      pages: ['Inicio', 'El estudio', 'Contacto', 'Proyectos', 'Rehabilitación', 'Ampliación', 'Local profesional', 'Viabilidad', 'Método', 'Honorarios', 'El equipo', 'Obras en curso', 'Prensa', 'Aviso legal', 'Mapa del sitio'],
      titre: 'Rehabilitar sin borrar',
      corps: 'Vivienda, casa tradicional y local profesional. Estudio de viabilidad antes de comprometer obra.',
      services: [
        { nom: 'Viabilidad', texte: 'Lo que permiten el edificio y la normativa, antes de comprometer obra.' },
        { nom: 'Rehabilitación', texte: 'Casa tradicional, edificio antiguo, nave: conservar lo que aguanta, rehacer el resto.' },
        { nom: 'Dirección de obra', texte: 'Consulta a empresas, visitas semanales y recepción de la obra.' },
      ],
      blocsRepris: ['El estudio', 'Nuestros proyectos', 'Escríbanos'],
      articles: [
        { titre: 'Hace falta arquitecto para una ampliación', requete: 'arquitecto obligatorio ampliación' },
        { titre: 'Rehabilitar una casa tradicional', requete: 'rehabilitación casa tradicional burdeos' },
        { titre: 'Cuánto cuesta un estudio de viabilidad', requete: 'precio estudio viabilidad arquitecto' },
        { titre: 'Licencia de obra o declaración previa', requete: 'licencia obra o declaración previa' },
        { titre: 'Aislar un muro de piedra sin cerrarlo', requete: 'aislamiento muro piedra antiguo' },
        { titre: 'Añadir una planta en la ciudad', requete: 'añadir planta vivienda burdeos' },
        { titre: 'Qué incluyen nuestros honorarios', requete: 'honorarios arquitecto porcentaje' },
        { titre: 'Trabajar con empresas locales', requete: 'arquitecto consulta empresas' },
        { titre: 'Convertir un local en vivienda', requete: 'cambio de uso local vivienda' },
        { titre: 'Obra con el edificio ocupado', requete: 'obras edificio ocupado' },
      ],
      recherche: { titre: 'Atelier Bastide · Arquitectos en Burdeos', description: 'Rehabilitación, ampliación y local profesional. Estudio de viabilidad antes de la obra.' },
    },
    de: {
      enseigne: 'Atelier Bastide',
      surtitre: 'Architekturbüro',
      pages: ['Startseite', 'Das Büro', 'Kontakt', 'Projekte', 'Sanierung', 'Anbau', 'Gewerbefläche', 'Machbarkeit', 'Methode', 'Honorare', 'Das Team', 'Laufende Baustellen', 'Presse', 'Impressum', 'Sitemap'],
      titre: 'Sanieren, ohne zu löschen',
      corps: 'Wohnraum, Stadthaus und Gewerbefläche. Machbarkeitsstudie, bevor Bauarbeiten vergeben werden.',
      services: [
        { nom: 'Machbarkeit', texte: 'Was Gebäude und Bauordnung zulassen, bevor Arbeiten vergeben werden.' },
        { nom: 'Sanierung', texte: 'Stadthaus, Altbau, Scheune: erhalten, was trägt, den Rest neu bauen.' },
        { nom: 'Bauleitung', texte: 'Ausschreibung, wöchentliche Besuche, Abnahme der Arbeiten.' },
      ],
      blocsRepris: ['Das Büro', 'Unsere Projekte', 'Schreiben Sie uns'],
      articles: [
        { titre: 'Braucht ein Anbau einen Architekten', requete: 'architekt pflicht anbau' },
        { titre: 'Ein Bordeaux-Stadthaus sanieren', requete: 'stadthaus sanierung bordeaux' },
        { titre: 'Was eine Machbarkeitsstudie kostet', requete: 'machbarkeitsstudie architekt preis' },
        { titre: 'Baugenehmigung oder Anzeige', requete: 'baugenehmigung oder anzeige' },
        { titre: 'Eine Steinwand dämmen, ohne sie zu ersticken', requete: 'dämmung steinwand altbau' },
        { titre: 'Aufstocken in der Stadt', requete: 'aufstockung haus bordeaux' },
        { titre: 'Was unsere Honorare umfassen', requete: 'architektenhonorar prozent' },
        { titre: 'Mit örtlichen Betrieben arbeiten', requete: 'architekt ausschreibung betriebe' },
        { titre: 'Aus einem Laden eine Wohnung machen', requete: 'nutzungsänderung laden wohnung' },
        { titre: 'Bauen im bewohnten Gebäude', requete: 'bauen im bewohnten gebäude' },
      ],
      recherche: { titre: 'Atelier Bastide · Architekten in Bordeaux', description: 'Sanierung, Anbau und Gewerbefläche. Machbarkeitsstudie vor der Vergabe.' },
    },
  },
  etudes: {
    fr: {
      enseigne: 'Bureau Estuaire',
      surtitre: 'Bureau d’études techniques',
      pages: ['Accueil', 'Le bureau', 'Contact', 'Structure', 'Thermique', 'Acoustique', 'Missions', 'Projets', 'Méthode', 'Outils de calcul', 'L’équipe', 'Recrutement', 'Documents', 'Mentions légales', 'Plan du site'],
      titre: 'Structure et thermique, calculées et signées',
      corps: 'Notes de calcul, études thermiques et assistance en phase chantier, pour architectes et maîtres d’ouvrage.',
      services: [
        { nom: 'Calcul de structure', texte: 'Béton, bois, métal : descentes de charges, notes de calcul, plans d’exécution.' },
        { nom: 'Étude thermique', texte: 'Réglementation en vigueur, simulations et attestations à chaque phase.' },
        { nom: 'Phase chantier', texte: 'Visas d’exécution, réponses aux entreprises, ajustements en cours de travaux.' },
      ],
      blocsRepris: ['Le bureau', 'Nos missions', 'Nous écrire'],
      articles: [
        { titre: 'À quel moment consulter un bureau d’études', requete: 'quand consulter bureau d’études' },
        { titre: 'Ce que contient une note de calcul', requete: 'note de calcul structure' },
        { titre: 'Étude thermique, ce qui est exigé', requete: 'étude thermique réglementation' },
        { titre: 'Ouvrir un mur porteur, la marche à suivre', requete: 'ouverture mur porteur étude' },
        { titre: 'Bois ou béton pour une extension', requete: 'structure bois ou béton' },
        { titre: 'Reprendre en sous-œuvre un bâti ancien', requete: 'reprise en sous-œuvre ancien' },
        { titre: 'Lire un rapport de sol', requete: 'lecture rapport étude de sol' },
        { titre: 'À quoi sert le visa d’exécution', requete: 'visa d’exécution bureau d’études' },
        { titre: 'Chiffrer une mission d’études', requete: 'coût mission bureau d’études' },
        { titre: 'Travailler avec l’architecte, pas contre lui', requete: 'bureau d’études architecte collaboration' },
      ],
      recherche: { titre: 'Bureau Estuaire · Structure et thermique en Gironde', description: 'Notes de calcul, études thermiques et assistance en phase chantier.' },
    },
    en: {
      enseigne: 'Bureau Estuaire',
      surtitre: 'Engineering consultancy',
      pages: ['Home', 'The office', 'Contact', 'Structure', 'Thermal', 'Acoustics', 'Services', 'Projects', 'Method', 'Calculation tools', 'The team', 'Careers', 'Documents', 'Legal', 'Sitemap'],
      titre: 'Structural and thermal engineering, calculated and signed',
      corps: 'Calculation notes, thermal studies and on-site support, for architects and building owners.',
      services: [
        { nom: 'Structural design', texte: 'Concrete, timber, steel: load paths, calculation notes, construction drawings.' },
        { nom: 'Thermal study', texte: 'Current regulations, simulations and certificates at every stage.' },
        { nom: 'On site', texte: 'Approval of shop drawings, answers to trades, adjustments as work goes on.' },
      ],
      blocsRepris: ['The office', 'Our services', 'Write to us'],
      articles: [
        { titre: 'When to bring in an engineering office', requete: 'when to hire structural engineer' },
        { titre: 'What a calculation note contains', requete: 'structural calculation note' },
        { titre: 'Thermal study, what is required', requete: 'thermal study regulation' },
        { titre: 'Opening a load-bearing wall, step by step', requete: 'load bearing wall opening study' },
        { titre: 'Timber or concrete for an extension', requete: 'timber or concrete structure' },
        { titre: 'Underpinning an old building', requete: 'underpinning old building' },
        { titre: 'Reading a soil report', requete: 'reading soil survey report' },
        { titre: 'What shop drawing approval is for', requete: 'shop drawing approval engineer' },
        { titre: 'Pricing an engineering brief', requete: 'engineering brief cost' },
        { titre: 'Working with the architect, not against them', requete: 'engineer architect collaboration' },
      ],
      recherche: { titre: 'Bureau Estuaire · Structural and thermal engineering', description: 'Calculation notes, thermal studies and support during construction.' },
    },
    es: {
      enseigne: 'Bureau Estuaire',
      surtitre: 'Oficina técnica',
      pages: ['Inicio', 'La oficina', 'Contacto', 'Estructura', 'Térmica', 'Acústica', 'Servicios', 'Proyectos', 'Método', 'Herramientas de cálculo', 'El equipo', 'Empleo', 'Documentos', 'Aviso legal', 'Mapa del sitio'],
      titre: 'Estructura y térmica, calculadas y firmadas',
      corps: 'Memorias de cálculo, estudios térmicos y asistencia en obra, para arquitectos y promotores.',
      services: [
        { nom: 'Cálculo de estructura', texte: 'Hormigón, madera, acero: bajada de cargas, memorias de cálculo, planos de ejecución.' },
        { nom: 'Estudio térmico', texte: 'Normativa vigente, simulaciones y certificados en cada fase.' },
        { nom: 'Fase de obra', texte: 'Visado de planos de taller, respuestas a las empresas y ajustes durante la obra.' },
      ],
      blocsRepris: ['La oficina', 'Nuestros servicios', 'Escríbanos'],
      articles: [
        { titre: 'Cuándo llamar a una oficina técnica', requete: 'cuándo contratar oficina técnica' },
        { titre: 'Qué contiene una memoria de cálculo', requete: 'memoria de cálculo estructura' },
        { titre: 'Estudio térmico, qué se exige', requete: 'estudio térmico normativa' },
        { titre: 'Abrir un muro de carga, paso a paso', requete: 'apertura muro de carga estudio' },
        { titre: 'Madera u hormigón para una ampliación', requete: 'estructura madera u hormigón' },
        { titre: 'Recalzar un edificio antiguo', requete: 'recalce edificio antiguo' },
        { titre: 'Leer un informe geotécnico', requete: 'leer informe geotécnico' },
        { titre: 'Para qué sirve el visado de taller', requete: 'visado planos taller ingeniería' },
        { titre: 'Presupuestar un encargo técnico', requete: 'coste encargo oficina técnica' },
        { titre: 'Trabajar con el arquitecto, no contra él', requete: 'ingeniería arquitecto colaboración' },
      ],
      recherche: { titre: 'Bureau Estuaire · Estructura y térmica en Gironda', description: 'Memorias de cálculo, estudios térmicos y asistencia durante la obra.' },
    },
    de: {
      enseigne: 'Bureau Estuaire',
      surtitre: 'Ingenieurbüro',
      pages: ['Startseite', 'Das Büro', 'Kontakt', 'Tragwerk', 'Wärmeschutz', 'Akustik', 'Leistungen', 'Projekte', 'Methode', 'Rechenwerkzeuge', 'Das Team', 'Karriere', 'Dokumente', 'Impressum', 'Sitemap'],
      titre: 'Tragwerk und Wärmeschutz, gerechnet und unterschrieben',
      corps: 'Statische Berechnungen, Wärmeschutznachweise und Baustellenbegleitung für Architekten und Bauherren.',
      services: [
        { nom: 'Tragwerksplanung', texte: 'Beton, Holz, Stahl: Lastabtrag, statische Berechnungen, Ausführungspläne.' },
        { nom: 'Wärmeschutz', texte: 'Geltende Vorschriften, Simulationen und Nachweise in jeder Phase.' },
        { nom: 'Bauphase', texte: 'Freigabe der Werkpläne, Antworten an die Betriebe, Anpassungen während der Arbeiten.' },
      ],
      blocsRepris: ['Das Büro', 'Unsere Leistungen', 'Schreiben Sie uns'],
      articles: [
        { titre: 'Wann ein Ingenieurbüro dazukommt', requete: 'wann ingenieurbüro beauftragen' },
        { titre: 'Was eine statische Berechnung enthält', requete: 'statische berechnung inhalt' },
        { titre: 'Wärmeschutznachweis, was verlangt wird', requete: 'wärmeschutznachweis vorschrift' },
        { titre: 'Eine tragende Wand öffnen, Schritt für Schritt', requete: 'tragende wand öffnen statik' },
        { titre: 'Holz oder Beton für einen Anbau', requete: 'tragwerk holz oder beton' },
        { titre: 'Einen Altbau unterfangen', requete: 'unterfangung altbau' },
        { titre: 'Ein Bodengutachten lesen', requete: 'bodengutachten lesen' },
        { titre: 'Wozu die Werkplanfreigabe dient', requete: 'werkplanfreigabe ingenieur' },
        { titre: 'Eine Ingenieurleistung kalkulieren', requete: 'kosten ingenieurleistung' },
        { titre: 'Mit dem Architekten arbeiten, nicht gegen ihn', requete: 'ingenieur architekt zusammenarbeit' },
      ],
      recherche: { titre: 'Bureau Estuaire · Tragwerk und Wärmeschutz', description: 'Statische Berechnungen, Wärmeschutznachweise und Begleitung auf der Baustelle.' },
    },
  },
  formation: {
    fr: {
      enseigne: 'Cap Décidé',
      surtitre: 'Formation et accompagnement',
      pages: ['Accueil', 'Les formations', 'Contact', 'Prise de parole', 'Accompagnement individuel', 'Ateliers d’équipe', 'Entreprises', 'Programme', 'Méthode', 'Tarifs', 'Financement', 'Calendrier', 'Ressources', 'Mentions légales', 'Plan du site'],
      titre: 'Prendre la parole sans la subir',
      corps: 'Formation à l’oral et accompagnement individuel, en présence à Bordeaux ou à distance.',
      services: [
        { nom: 'Prise de parole', texte: 'Deux jours pour préparer, structurer et tenir une intervention debout.' },
        { nom: 'Accompagnement individuel', texte: 'Six séances, un objectif écrit au départ, un bilan à la fin.' },
        { nom: 'Ateliers d’équipe', texte: 'Des réunions plus courtes, des décisions plus nettes, des rôles clarifiés.' },
      ],
      blocsRepris: ['Les formations', 'La méthode', 'Nous écrire'],
      articles: [
        { titre: 'Le trac avant une présentation', requete: 'gérer le trac présentation' },
        { titre: 'Structurer une intervention de dix minutes', requete: 'structurer présentation dix minutes' },
        { titre: 'Coaching ou formation, quelle différence', requete: 'coaching ou formation différence' },
        { titre: 'Financer une formation', requete: 'financement formation professionnelle' },
        { titre: 'Animer une réunion qui décide', requete: 'animer une réunion efficace' },
        { titre: 'Parler devant une caméra', requete: 'prise de parole caméra' },
        { titre: 'Préparer un entretien annuel', requete: 'préparer entretien annuel' },
        { titre: 'Répondre à une question hostile', requete: 'répondre question difficile public' },
        { titre: 'Ce qui se passe en première séance', requete: 'première séance accompagnement' },
        { titre: 'Travailler sa voix sans forcer', requete: 'travailler sa voix à l’oral' },
      ],
      recherche: { titre: 'Cap Décidé · Formation à l’oral à Bordeaux', description: 'Prise de parole, accompagnement individuel et ateliers d’équipe, en présence ou à distance.' },
    },
    en: {
      enseigne: 'Cap Décidé',
      surtitre: 'Training and coaching',
      pages: ['Home', 'Courses', 'Contact', 'Public speaking', 'One to one', 'Team workshops', 'Business', 'Programme', 'Method', 'Fees', 'Funding', 'Calendar', 'Resources', 'Legal', 'Sitemap'],
      titre: 'Speaking up without dreading it',
      corps: 'Public speaking courses and one to one coaching, in Bordeaux or remotely.',
      services: [
        { nom: 'Public speaking', texte: 'Two days to prepare, structure and hold a talk on your feet.' },
        { nom: 'One to one', texte: 'Six sessions, one goal written down at the start, a review at the end.' },
        { nom: 'Team workshops', texte: 'Shorter meetings, clearer decisions, roles everyone can name.' },
      ],
      blocsRepris: ['Our courses', 'The method', 'Write to us'],
      articles: [
        { titre: 'Stage fright before a presentation', requete: 'handling stage fright presentation' },
        { titre: 'Structuring a ten minute talk', requete: 'structure ten minute talk' },
        { titre: 'Coaching or training, what differs', requete: 'coaching or training difference' },
        { titre: 'Funding a course', requete: 'professional training funding' },
        { titre: 'Running a meeting that decides', requete: 'running an effective meeting' },
        { titre: 'Speaking to a camera', requete: 'speaking to camera tips' },
        { titre: 'Preparing an annual review', requete: 'preparing annual review' },
        { titre: 'Answering a hostile question', requete: 'answering hostile question audience' },
        { titre: 'What happens in the first session', requete: 'first coaching session' },
        { titre: 'Using your voice without straining', requete: 'voice training speaking' },
      ],
      recherche: { titre: 'Cap Décidé · Public speaking courses in Bordeaux', description: 'Public speaking, one to one coaching and team workshops, in person or remotely.' },
    },
    es: {
      enseigne: 'Cap Décidé',
      surtitre: 'Formación y acompañamiento',
      pages: ['Inicio', 'Formaciones', 'Contacto', 'Hablar en público', 'Acompañamiento individual', 'Talleres de equipo', 'Empresas', 'Programa', 'Método', 'Tarifas', 'Financiación', 'Calendario', 'Recursos', 'Aviso legal', 'Mapa del sitio'],
      titre: 'Hablar en público sin padecerlo',
      corps: 'Formación en oratoria y acompañamiento individual, en Burdeos o a distancia.',
      services: [
        { nom: 'Hablar en público', texte: 'Dos días para preparar, estructurar y sostener una intervención de pie.' },
        { nom: 'Acompañamiento individual', texte: 'Seis sesiones, un objetivo escrito al inicio y un balance al final.' },
        { nom: 'Talleres de equipo', texte: 'Reuniones más cortas, decisiones más claras, papeles definidos.' },
      ],
      blocsRepris: ['Nuestras formaciones', 'El método', 'Escríbanos'],
      articles: [
        { titre: 'El miedo antes de una presentación', requete: 'gestionar miedo presentación' },
        { titre: 'Estructurar una intervención de diez minutos', requete: 'estructurar presentación diez minutos' },
        { titre: 'Coaching o formación, qué cambia', requete: 'coaching o formación diferencia' },
        { titre: 'Financiar una formación', requete: 'financiación formación profesional' },
        { titre: 'Dirigir una reunión que decide', requete: 'dirigir reunión eficaz' },
        { titre: 'Hablar ante una cámara', requete: 'hablar ante cámara consejos' },
        { titre: 'Preparar una evaluación anual', requete: 'preparar evaluación anual' },
        { titre: 'Responder a una pregunta hostil', requete: 'responder pregunta hostil público' },
        { titre: 'Qué pasa en la primera sesión', requete: 'primera sesión acompañamiento' },
        { titre: 'Trabajar la voz sin forzarla', requete: 'trabajar la voz oratoria' },
      ],
      recherche: { titre: 'Cap Décidé · Formación en oratoria en Burdeos', description: 'Oratoria, acompañamiento individual y talleres de equipo, presenciales o a distancia.' },
    },
    de: {
      enseigne: 'Cap Décidé',
      surtitre: 'Training und Begleitung',
      pages: ['Startseite', 'Die Kurse', 'Kontakt', 'Reden halten', 'Einzelbegleitung', 'Teamworkshops', 'Firmen', 'Programm', 'Methode', 'Preise', 'Förderung', 'Termine', 'Material', 'Impressum', 'Sitemap'],
      titre: 'Reden halten, ohne sie zu erleiden',
      corps: 'Rhetoriktraining und Einzelbegleitung, in Bordeaux oder aus der Ferne.',
      services: [
        { nom: 'Reden halten', texte: 'Zwei Tage, um einen Auftritt vorzubereiten, zu gliedern und zu tragen.' },
        { nom: 'Einzelbegleitung', texte: 'Sechs Sitzungen, ein zu Beginn schriftlich gefasstes Ziel, am Ende eine Bilanz.' },
        { nom: 'Teamworkshops', texte: 'Kürzere Besprechungen, klarere Entscheidungen, benannte Rollen.' },
      ],
      blocsRepris: ['Unsere Kurse', 'Die Methode', 'Schreiben Sie uns'],
      articles: [
        { titre: 'Lampenfieber vor einem Vortrag', requete: 'lampenfieber vortrag bewältigen' },
        { titre: 'Einen Zehnminutenvortrag gliedern', requete: 'vortrag zehn minuten gliedern' },
        { titre: 'Coaching oder Schulung, was unterscheidet sie', requete: 'coaching oder schulung unterschied' },
        { titre: 'Eine Weiterbildung finanzieren', requete: 'weiterbildung finanzierung' },
        { titre: 'Eine Besprechung führen, die entscheidet', requete: 'besprechung wirksam führen' },
        { titre: 'Vor der Kamera sprechen', requete: 'vor der kamera sprechen tipps' },
        { titre: 'Ein Jahresgespräch vorbereiten', requete: 'jahresgespräch vorbereiten' },
        { titre: 'Auf eine feindliche Frage antworten', requete: 'feindliche frage publikum antworten' },
        { titre: 'Was in der ersten Sitzung passiert', requete: 'erste sitzung begleitung' },
        { titre: 'Die Stimme führen, ohne zu drücken', requete: 'stimmtraining sprechen' },
      ],
      recherche: { titre: 'Cap Décidé · Rhetoriktraining in Bordeaux', description: 'Reden halten, Einzelbegleitung und Teamworkshops, vor Ort oder aus der Ferne.' },
    },
  },
  autre: {
    fr: {
      enseigne: 'Votre entreprise',
      surtitre: 'Votre secteur, votre ville',
      pages: ['Accueil', 'Services', 'Contact', 'Tarifs', 'Réalisations', 'À propos', 'Équipe', 'FAQ', 'Blog', 'Presse', 'Partenaires', 'Recrutement', 'Documents', 'Mentions', 'Plan'],
      titre: 'Votre activité, dite clairement',
      corps: 'Ce que vous faites, pour qui, et comment vous joindre. Le reste vient après.',
      services: [
        { nom: 'Votre premier service', texte: 'Une phrase qui dit ce que le client obtient, pas ce que vous faites.' },
        { nom: 'Votre deuxième service', texte: 'Le même effort, appliqué à ce qui vous distingue vraiment.' },
        { nom: 'Votre troisième service', texte: 'Trois suffisent : au-delà, personne ne lit la liste.' },
      ],
      blocsRepris: ['Nos services', 'Notre histoire', 'Nous contacter'],
      articles: [
        { titre: 'Ce que cherchent vos clients', requete: 'votre métier votre ville' },
        { titre: 'Combien coûte votre prestation', requete: 'prix votre prestation' },
        { titre: 'Un premier rendez-vous', requete: 'premier rendez-vous métier' },
        { titre: 'Vos délais, sans détour', requete: 'délai votre prestation' },
        { titre: 'Choisir un professionnel', requete: 'votre métier près de moi' },
        { titre: 'Les questions fréquentes', requete: 'questions fréquentes métier' },
        { titre: 'Ce que votre devis comprend', requete: 'devis votre métier' },
        { titre: 'Travailler avec vous', requete: 'déroulé de la prestation' },
        { titre: 'Les erreurs les plus vues', requete: 'erreurs fréquentes métier' },
        { titre: 'Où vous intervenez', requete: 'zone d’intervention' },
      ],
      recherche: { titre: 'Votre entreprise · Votre activité, votre ville', description: 'Ce que vous faites, pour qui, et comment vous joindre. Description reprise de votre page d’accueil.' },
    },
    en: {
      enseigne: 'Your company',
      surtitre: 'Your sector, your town',
      pages: ['Home', 'Services', 'Contact', 'Pricing', 'Projects', 'About', 'Team', 'FAQ', 'Blog', 'Press', 'Partners', 'Careers', 'Documents', 'Legal', 'Sitemap'],
      titre: 'Your business, said plainly',
      corps: 'What you do, who for, and how to reach you. The rest comes later.',
      services: [
        { nom: 'Your first service', texte: 'One sentence saying what the client gets, not what you do.' },
        { nom: 'Your second service', texte: 'The same effort, applied to what really sets you apart.' },
        { nom: 'Your third service', texte: 'Three is enough: past that, nobody reads the list.' },
      ],
      blocsRepris: ['Our services', 'Our story', 'Get in touch'],
      articles: [
        { titre: 'What clients look up', requete: 'your trade your town' },
        { titre: 'What your service costs', requete: 'price of your service' },
        { titre: 'A first meeting', requete: 'first meeting your trade' },
        { titre: 'Your lead times', requete: 'lead time your service' },
        { titre: 'Choosing a professional', requete: 'your trade near me' },
        { titre: 'The questions we get', requete: 'frequently asked trade' },
        { titre: 'What your quote covers', requete: 'quote your trade' },
        { titre: 'Working with you', requete: 'process your trade' },
        { titre: 'The mistakes we see', requete: 'common mistakes trade' },
        { titre: 'Where you work', requete: 'your trade service area' },
      ],
      recherche: { titre: 'Your company · Your business, your town', description: 'What you do, who for, and how to reach you. Description taken from your home page.' },
    },
    es: {
      enseigne: 'Su empresa',
      surtitre: 'Su sector, su ciudad',
      pages: ['Inicio', 'Servicios', 'Contacto', 'Tarifas', 'Proyectos', 'Nosotros', 'Equipo', 'FAQ', 'Blog', 'Prensa', 'Socios', 'Empleo', 'Documentos', 'Aviso legal', 'Mapa'],
      titre: 'Su actividad, dicha con claridad',
      corps: 'Lo que hace, para quién, y cómo contactarle. El resto viene después.',
      services: [
        { nom: 'Su primer servicio', texte: 'Una frase que diga lo que obtiene el cliente, no lo que usted hace.' },
        { nom: 'Su segundo servicio', texte: 'El mismo esfuerzo, aplicado a lo que de verdad le distingue.' },
        { nom: 'Su tercer servicio', texte: 'Tres bastan: más allá, nadie lee la lista.' },
      ],
      blocsRepris: ['Nuestros servicios', 'Nuestra historia', 'Contactar'],
      articles: [
        { titre: 'Lo que buscan sus clientes', requete: 'su oficio su ciudad' },
        { titre: 'Cuánto cuesta su servicio', requete: 'precio de su servicio' },
        { titre: 'Una primera cita', requete: 'primera cita su oficio' },
        { titre: 'Sus plazos, sin rodeos', requete: 'plazo de su servicio' },
        { titre: 'Elegir un profesional', requete: 'su oficio cerca de mí' },
        { titre: 'Las preguntas frecuentes', requete: 'preguntas frecuentes oficio' },
        { titre: 'Qué incluye su presupuesto', requete: 'presupuesto su oficio' },
        { titre: 'Trabajar con usted', requete: 'proceso su oficio' },
        { titre: 'Los errores más vistos', requete: 'errores frecuentes oficio' },
        { titre: 'Dónde trabaja', requete: 'su oficio zona de trabajo' },
      ],
      recherche: { titre: 'Su empresa · Su actividad, su ciudad', description: 'Lo que hace, para quién, y cómo contactarle. Descripción tomada de su página de inicio.' },
    },
    de: {
      enseigne: 'Ihr Unternehmen',
      surtitre: 'Ihre Branche, Ihre Stadt',
      pages: ['Startseite', 'Leistungen', 'Kontakt', 'Preise', 'Projekte', 'Über uns', 'Team', 'FAQ', 'Blog', 'Presse', 'Partner', 'Karriere', 'Dokumente', 'Impressum', 'Sitemap'],
      titre: 'Ihre Tätigkeit, klar gesagt',
      corps: 'Was Sie tun, für wen, und wie man Sie erreicht. Der Rest kommt danach.',
      services: [
        { nom: 'Ihre erste Leistung', texte: 'Ein Satz, der sagt, was der Kunde bekommt, nicht was Sie tun.' },
        { nom: 'Ihre zweite Leistung', texte: 'Derselbe Aufwand, angewandt auf das, was Sie wirklich auszeichnet.' },
        { nom: 'Ihre dritte Leistung', texte: 'Drei genügen: darüber hinaus liest niemand die Liste.' },
      ],
      blocsRepris: ['Unsere Leistungen', 'Unsere Geschichte', 'Kontakt aufnehmen'],
      articles: [
        { titre: 'Was Kunden nachsehen', requete: 'ihr gewerbe ihre stadt' },
        { titre: 'Was Ihre Leistung kostet', requete: 'preis ihrer leistung' },
        { titre: 'Ein erstes Gespräch', requete: 'erstes gespräch gewerbe' },
        { titre: 'Ihre Fristen, klar benannt', requete: 'frist ihrer leistung' },
        { titre: 'Einen Fachbetrieb wählen', requete: 'gewerbe in der nähe' },
        { titre: 'Die häufigen Fragen', requete: 'häufige fragen gewerbe' },
        { titre: 'Was Ihr Angebot umfasst', requete: 'angebot ihr gewerbe' },
        { titre: 'Mit Ihnen arbeiten', requete: 'ablauf ihr gewerbe' },
        { titre: 'Die häufigsten Fehler', requete: 'häufige fehler gewerbe' },
        { titre: 'Wo Sie arbeiten', requete: 'gewerbe einsatzgebiet' },
      ],
      recherche: { titre: 'Ihr Unternehmen · Ihre Tätigkeit, Ihre Stadt', description: 'Was Sie tun, für wen, und wie man Sie erreicht. Beschreibung von Ihrer Startseite übernommen.' },
    },
  },
}

/** Un identifiant inconnu retombe sur le domaine générique : un lien partagé trafiqué
 *  ne doit pas rendre une maquette à trous. */
export function editorialDe(domaine: string, langue: Langue): Editorial {
  return EDITORIAL[domaine as DomaineId]?.[langue] ?? EDITORIAL[DOMAINE_DEFAUT][langue]
}
